### ISSUE TITLE
AttributeError: 'long' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by Firework471** [trailofbits/ida-evm#1]
Hi:
I have followed the instruction to install the IDA Pro and copy the .py files into specified directory. But the following error occurs when I start the IDA Pro:
Traceback (most recent call last):

  File "/home/zhutong/IDA_Pro_v6.4_(Linux)_and_Hex-Rays_Decompiler_(ARM)/loaders/evm-loader.py", line 8, in accept_file
    if filename.endswith('.evm') or filename.endswith('.bytecode'):
AttributeError: 'long' object has no attribute 'endswith'

I will appreciate it if you can help me.

**Comment by computerality** [comment]
ida-evm currently only supports IDA Pro 7.0 and newer due to backwards-incompatible changes in the processor module API.

For the specifics of this error, IDA changed an argument that used to be the recursive depth of the loader being called to be a more useful argument, the filename.

**Comment by TONGZHU95** [comment]
So I only need to update my IDA or I need to do something else on the IDA?
